{{- if .Values.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: okapi-{{ .Release.Name }}
  labels:
    app: {{ template "tenant.name" $ }}
    chart: {{ template "tenant.chart" $ }}
    release: {{ .Release.Name }}
    heritage: {{ $.Release.Service }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.classname | default "nginx" }}
  tls:
{{- range .Values.ingress.tls }}
  - hosts:
  {{- if .hosts }}
    {{- range .hosts }}
    - {{ . }}
    {{- end }}
  {{- else }}
    - {{ .host }}
  {{- end }}
    secretName: {{ .secretName }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.global.okapi.ingressPath | default "/okapi/(.*)" }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.global.okapi.serviceName | default "okapi" }}
                port:
                  number: {{ .Values.global.okapi.port | default "9130" }}
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: stripes--{{ .Release.Name }}
  labels:
    app: {{ template "tenant.name" $ }}
    chart: {{ template "tenant.chart" $ }}
    release: {{ .Release.Name }}
    heritage: {{ $.Release.Service }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.classname | default "nginx" }}
  tls:
{{- range .Values.ingress.tls }}
  - hosts:
  {{- if .hosts }}
    {{- range .hosts }}
    - {{ . }}
    {{- end }}
  {{- else }}
    - {{ .host }}
  {{- end }}
    secretName: {{ .secretName }}
{{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - path: {{ .ingress.path | default "/" }}
          pathType: Prefix
          backend:
            service:
              name: {{ $.Release.Name }}-{{.tenantId}}
              port:
                number: {{ .stripes.port | default "80" }}
{{- end }}
