apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-env
data:
  OKAPI_URL: http://{{ include "okapi.fullname" . }}:{{ .Values.service.port | default "9130" }}
  OKAPI_HOST: {{ include "okapi.fullname" . }}
  OKAPI_PORT: "{{ .Values.service.port | default "9130" }}"
  OKAPI_CONFIG_FILE: /etc/okapi/okapi-config.json
  OKAPI_NODENAME: $(hostname)
  OKAPI_LOGLEVEL: INFO
  OKAPI_CLUSTERHOST: {{ include "okapi.fullname" . }}
  OKAPI_STORAGE: postgres
  HAZELCAST_VERTX_PORT: "5702"
  HAZELCAST_PORT: "5701"
  HAZELCAST_IP: {{ include "okapi.fullname" . }}
  KUBE_SERVER_URL: https://kubernetes.default
  KUBE_SERVER_PEM: /etc/kubernetes/ssl/ca.crt
  KUBE_NAMESPACE: {{ .Release.Namespace }}
{{- if eq $.Values.global.okapi.mode "cluster" }}
  OKAPI_COMMAND: "cluster"
  HAZELCAST_FILE: /etc/hazelcast/hazelcast.xml
{{- end }}

{{- with .Values.global.okapi.environment }}
{{- toYaml . | indent 2 }}
{{- end }}

{{- if eq $.Values.global.okapi.mode "cluster" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: okapi-hazelcast-config-{{ .Release.Name }}
data:
{{ ( tpl (.Files.Glob "files/hazelcast.xml").AsConfig . ) | indent 2 }}
{{- end }}

