apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-discovery-account
secrets:
  - name: {{ .Release.Name }}-discovery-token
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-discovery
  annotations:
    kubernetes.io/service-account.name: {{ .Release.Name }}-discovery-account
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-discovery-role
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - pods
      - nodes
      - services
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-discovery-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-discovery-role
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-discovery-account
